config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboards#index'

  devise_for :users

  get 'admins/index'
  get 'superadmins/index'

  get 'bookings/show'
  get 'bookings/book/:id' => 'bookings#create_booking', as: :create_booking
  get 'addresses/create/:id' => 'addresses#new', as: :create_address
  get 'view_user' => 'users#view', as: :view_user
  get 'view_addr/:id' => 'users#view_addr', as: :view_addr
  get 'driver/approve' => 'drivers#approve', as: :driver_approval
  get 'driver/request_approved/:id' => 'driver_requests#accept_request', as: :request_accepted
  get 'driver/request_rejected/:id' => 'driver_requests#reject_request', as: :request_rejected

  # get 'superadmins/add_driver' => "superadmins#add_driver", as: :add_driver
  # post 'bookings/book/:id' => "bookings#create_booking", as: :create_booking
  # get "users/show/:id" => "users#show", as: :show_user

  resources 'drivers' do
    get 'show_booking', on: :collection, action: 'show_booking', as: :show_booking
  end
  resources 'bills', except: :new do
    get 'new_bill/:id', on: :collection, action: 'new', as: :new_bill
    get 'bill_pdf/:id', on: :collection, action: 'bill_pdf', as: :bill_pdf, defaults: { format: 'pdf' }
  end
  resources 'bookings' do
    get 'view_booking', on: :collection, action: 'view_booking', as: :view_booking
  end
  resources 'addresses'
  resources 'travels'
  resources 'cars'
  resources 'car_types'
  resources 'car_fuels'
  resources 'users', except: :create do
    post 'create_user', on: :collection, action: 'create', as: :create_user
  end
  resources 'customers'
  resources 'dashboards', only: [:index] do
    get 'about', on: :collection, action: 'about', as: :about
    get 'contact', on: :collection, action: 'contact', as: :contact
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car_fuel.rb
# frozen_string_literal: true

class CarFuel < ApplicationRecord
  has_many :cars

  validates :name, uniqueness: true
end

app/controllers/car_fuels_controller.rb
# frozen_string_literal: true

class CarFuelsController < ApplicationController
  before_action :set_car_fuel, only: %i[show edit update destroy]

  def index
    @car_fuels = CarFuel.all
  end

  def new
    @car_fuel = CarFuel.new
  end

  def edit; end

  def create
    @car_fuel = CarFuel.new(car_fuel_params)

    respond_to do |format|
      if @car_fuel.save
        flash[:success] = 'Car fuel Created Successfully'
        format.html { redirect_to new_car_fuel_path }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @car_fuel.update(car_fuel_params)
        flash[:success] = 'Car Fuel Updated Successfully'
        format.html { redirect_to @car_fuel }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @car_fuel.destroy
    respond_to do |format|
      flash[:danger] = 'Car Fuel Destroyed Successfully'
      format.html { redirect_to car_fuels_url }
    end
  end

  private

  def set_car_fuel
    @car_fuel = CarFuel.find(params[:id])
  end

  def car_fuel_params
    params.require(:car_fuel).permit(:name)
  end
end

app/helpers/car_fuels_helper.rb
# frozen_string_literal: true

module CarFuelsHelper
end

app/views/car_fuels/_form.html.erb
<%= form_with(model: carfuel, local: true) do |f| %>
  <div class="field">
    <%= f.label :Type_Name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>
  <br/><br/>
  <div class="actions">
    <%= f.submit "Add Fuel", class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/car_fuels/edit.html.erb
<h1>Editing Car Type</h1>

<%= render 'form', carfuel: @car_fuel %>
<br/><br/>
<%= link_to 'Back', car_fuels_path %>

app/views/car_fuels/index.html.erb
<%= render 'cars/links_car' %>
<br/><br/>
<h1>Car Fuels</h1>

<table class="table table-striped table-dark">
  <thead class = "bg-info">
    <tr>
      <th>Name</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @car_fuels.each do |car_fuel| %>
      <tr>
        <td><%= car_fuel.name %></td>
        <td> <%= link_to edit_car_type_path(car_fuel) do  %>
          <%= '<i class="fa fa-pencil-square-o text-light" aria-hidden="true"></i>'.html_safe %>
        <% end %></td>
        <td> <%= link_to car_fuel, method: :delete, data: { confirm: 'Are you sure?' } do  %>
            <%= '<i class="fa fa-trash text-light" aria-hidden="true"></i>'.html_safe %>
        <% end %></td>   
      </tr>
    <% end %>
  </tbody>
</table>

app/views/car_fuels/new.html.erb
<%= render 'cars/links_car' %>
<br/><br/>

<h1>New Car Fuel</h1>

<%= render 'form', carfuel: @car_fuel %>