config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboards#index'

  devise_for :users

  get 'admins/index'
  get 'superadmins/index'

  get 'bookings/show'
  get 'bookings/book/:id' => 'bookings#create_booking', as: :create_booking
  get 'addresses/create/:id' => 'addresses#new', as: :create_address
  get 'view_user' => 'users#view', as: :view_user
  get 'view_addr/:id' => 'users#view_addr', as: :view_addr
  get 'driver/approve' => 'drivers#approve', as: :driver_approval
  get 'driver/request_approved/:id' => 'driver_requests#accept_request', as: :request_accepted
  get 'driver/request_rejected/:id' => 'driver_requests#reject_request', as: :request_rejected

  # get 'superadmins/add_driver' => "superadmins#add_driver", as: :add_driver
  # post 'bookings/book/:id' => "bookings#create_booking", as: :create_booking
  # get "users/show/:id" => "users#show", as: :show_user

  resources 'drivers' do
    get 'show_booking', on: :collection, action: 'show_booking', as: :show_booking
  end
  resources 'bills', except: :new do
    get 'new_bill/:id', on: :collection, action: 'new', as: :new_bill
    get 'bill_pdf/:id', on: :collection, action: 'bill_pdf', as: :bill_pdf, defaults: { format: 'pdf' }
  end
  resources 'bookings' do
    get 'view_booking', on: :collection, action: 'view_booking', as: :view_booking
  end
  resources 'addresses'
  resources 'travels'
  resources 'cars'
  resources 'car_types'
  resources 'car_fuels'
  resources 'users', except: :create do
    post 'create_user', on: :collection, action: 'create', as: :create_user
  end
  resources 'customers'
  resources 'dashboards', only: [:index] do
    get 'about', on: :collection, action: 'about', as: :about
    get 'contact', on: :collection, action: 'contact', as: :contact
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  rolify
  has_one :users_role
  has_one :customer, dependent: :destroy
  has_one :driver
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :add_default_role, :add_user

  validates :fname, :lname, :contact, :dob, :gender,
            presence: true
  
  validates :email,
            uniqueness: true, 
            format: {with: /\A[a-zA-Z]+[\.?\w]*@([a-zA-Z])+(\.[a-z]{2,3})+\Z/,
            message: "Invalid Format Of Email ID..!!"}, if: :email_present?
  
  validates :password,
            length: {minimum: 8},
            confirmation: true, if: :password_present?

  # validates :password_confirmation, 
            # presence: true, if: :password_present?

  GENDER = %w[Male Female Other].freeze
  ROLE = %w[driver admin].freeze

  # default_scope { eager_load(users_role: :role) }

  private

  def email_present?
    email.present?
  end

  def password_present?
    password.present?
  end

  def add_default_role
    add_role(:customer) if roles.blank?
  end

  def add_user
    if has_role? :customer
      Customer.create!(user: self)
    elsif has_role? :driver
      Driver.create!(user: self)
    end
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_params, only: [:create]
  before_action :set_role, only: [:create]

  def index
    byebug
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(set_params)
    role = set_role[:role].downcase
    @user.add_role role
    if @user.save
      flash[:success] = 'Successfully User Created With Role: ' + role
      if @user.has_role? :driver
        redirect_to edit_driver_path(@user)
      else
        redirect_to root_path
      end
    else
      render 'new'
    end

    # byebug
  end

  def view
    @users = User.all
  end

  def view_addr
    @address = Address.where('user_id=?', params[:id])
  end

  private

  def set_id
    params.permit(:id)
  end

  def set_role
    params.require(:user).permit(:role)
  end

  def set_params
    params.require(:user).permit(:fname, :lname, :contact, :dob, :gender, :email, :password)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: @user,url: create_user_users_path  , local: true,method: :post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <% if current_user.has_role? :superadmin %>
    <div class="field">
      <%= f.label :role %>&nbsp;&nbsp;
      <%= f.select :role,User::ROLE.map(&:capitalize), {},{class: "btn btn-dark dropdown-toggle"} %>
    </div><br/>
  <% end %>
  <div class="field">
    <%= f.label :First_name %>&nbsp;&nbsp;
    <%= f.text_field :fname, autofocus: true %><br /><br />
  </div>

  <div class="field">
    <%= f.label :Last_Name %>&nbsp;&nbsp;
    <%= f.text_field :lname, autofocus: true %><br /><br />
  </div>

  <div class="field">
    <%= f.label :Contact_No %>&nbsp;&nbsp;
    <%= f.text_field :contact %><br /><br />
  </div>

  <div class="field">
    <%= f.label :Birth_Date %>&nbsp;&nbsp;
    <%= f.date_field :dob %><br /><br />
  </div>

  <div class="field">
    <%= f.label :gender %>&nbsp;&nbsp;
    <%= f.select :gender,User::GENDER, {},{class: "btn btn-dark dropdown-toggle"} %><br/><br/>
  </div>

  <div class="field">
    <%= f.label :email %>&nbsp;&nbsp;
    <%= f.email_field :email %><br/><br />
  </div>

  <div class="field">
    <%= f.label :password %>&nbsp;&nbsp;
    <%= f.password_field :password%><br/><br />
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>&nbsp;&nbsp;
    <%= f.password_field :password_confirmation %><br/><br />
  </div>

  <br /><br />

  <% if current_user.has_role? :admin %>

   <div class="hidden-role">
        <%= f.hidden_field :role, :value => "driver" %>
    </div>
  <% end %>
  
  <div class="actions">
    <%= f.submit "Add User" %>
  </div>

 

<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/view.html.erb
<h1>Users</h1>

<table class="table table-striped table-dark">
        <thead class = "bg-info">
            <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Contact</th>
            <th>Date Of Birth</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Role</th>
            <th>User Personal<br/> Details</th>
            <th>Address</th>
            <th>Edit</th>
            <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            <% @users.each do |user| %>
                <tr>
                    <td><%= user.fname %></td>
                    <td><%=  user.lname%></td>
                    <td><%= user.contact  %></td>
                    <td><%= user.dob %></td>
                    <td> <%= user.gender %></td>
                    <td> <%= user.email %> </td>
                    <td> <%= user.roles.first.name.capitalize %> </td>
                    <td><% if user.roles.first.name == 'driver' %>
                      <%= link_to edit_driver_path(user.id) do  %>
                      <%= '<i class="fa fa-pencil-square-o text-light" aria-hidden="true"></i>'.html_safe %>
                      <% end %>/
                      <%= link_to driver_path(user.id) do  %>
                      <%= '<i class="fa fa-eye text-light" aria-hidden="true"></i>'.html_safe %>
                      <% end %>
                    <%end%>
                    <% if user.roles.first.name == 'customer' %>
                      <%= link_to edit_customer_path(user.id) do  %>
                      <%= '<i class="fa fa-pencil-square-o text-light" aria-hidden="true"></i>'.html_safe %>
                      <% end %>/
                      <%= link_to customer_path(user.id) do  %>
                      <%= '<i class="fa fa-eye text-light" aria-hidden="true"></i>'.html_safe %>
                      <% end %>
                    <%end%></td>
                    <td><%= link_to view_addr_path(user.id) do  %>
                        <%= '<i class="fa fa-map-marker text-light" aria-hidden="true"></i>'.html_safe %>
                        <% end %> 
                    </td>
                    <% if user.roles.first.name != 'superadmin' %>
                    <td> <%= link_to '#' do  %>
                        <%= '<i class="fa fa-pencil-square-o text-light" aria-hidden="true"></i>'.html_safe %>
                        <% end %> 
                    </td>
                    <td> <%= link_to '#' do  %>
                        <%= '<i class="fa fa-trash text-light" aria-hidden="true"></i>'.html_safe %>
                        <% end %> 
                    </td>
                    <% end %>
                    
                </tr>
            <% end %>
        </tbody>
    </table>



     

app/views/users/view_addr.html.erb
<% if !@address.empty? %>
    <h1><%= @address.first.user.fname%> Address</h1>
<%else%>
    <h1>No Address Yet For <%= User.find_by(params[:id]).fname%></h1>
<% end%>

<table class="table table-striped table-dark">
        <thead class = "bg-info">
            <tr>
            <th>Location</th>
            <th>City</th>
            <th>State</th>
            <th>Zipcode</th>
            <th>Edit</th>
            <th>Delete</th>
            </tr>
        </thead>

        <tbody>
            <% @address.each do |add| %>
                <tr>
                    <td><%= add.location %></td>
                    <td><%=  add.city%></td>
                    <td><%= CS.states(:in)[add.state.to_sym]  %></td>
                    <td><%= add.zip %></td>
                    <td> <%= link_to edit_address_path(add) do  %>
                        <%= '<i class="fa fa-pencil-square-o text-light" aria-hidden="true"></i>'.html_safe %>
                        <% end %> 
                    </td>
                    <td> <%= link_to add, method: :delete, data: { confirm: 'Are you sure?' } do  %>
                        <%= '<i class="fa fa-trash text-light" aria-hidden="true"></i>'.html_safe %>
                        <% end %> 
                    </td>   
                </tr>
            <% end %>
        </tbody>
    </table>

<br/><br/><br/>
    <%= link_to 'Add New Address',new_address_path, class: "btn btn-outline-primary btn-lg" %>
 