config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboards#index'

  devise_for :users

  get 'admins/index'
  get 'superadmins/index'

  get 'bookings/show'
  get 'bookings/book/:id' => 'bookings#create_booking', as: :create_booking
  get 'addresses/create/:id' => 'addresses#new', as: :create_address
  get 'view_user' => 'users#view', as: :view_user
  get 'view_addr/:id' => 'users#view_addr', as: :view_addr
  get 'driver/approve' => 'drivers#approve', as: :driver_approval
  get 'driver/request_approved/:id' => 'driver_requests#accept_request', as: :request_accepted
  get 'driver/request_rejected/:id' => 'driver_requests#reject_request', as: :request_rejected

  # get 'superadmins/add_driver' => "superadmins#add_driver", as: :add_driver
  # post 'bookings/book/:id' => "bookings#create_booking", as: :create_booking
  # get "users/show/:id" => "users#show", as: :show_user

  resources 'drivers' do
    get 'show_booking', on: :collection, action: 'show_booking', as: :show_booking
  end
  resources 'bills', except: :new do
    get 'new_bill/:id', on: :collection, action: 'new', as: :new_bill
    get 'bill_pdf/:id', on: :collection, action: 'bill_pdf', as: :bill_pdf, defaults: { format: 'pdf' }
  end
  resources 'bookings' do
    get 'view_booking', on: :collection, action: 'view_booking', as: :view_booking
  end
  resources 'addresses'
  resources 'travels'
  resources 'cars'
  resources 'car_types'
  resources 'car_fuels'
  resources 'users', except: :create do
    post 'create_user', on: :collection, action: 'create', as: :create_user
  end
  resources 'customers'
  resources 'dashboards', only: [:index] do
    get 'about', on: :collection, action: 'about', as: :about
    get 'contact', on: :collection, action: 'contact', as: :contact
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/driver.rb
# frozen_string_literal: true

class Driver < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :licence_driver_image
  has_one_attached :driver_image
  has_many :driver_requests
end

app/controllers/drivers_controller.rb
# frozen_string_literal: true

class DriversController < ApplicationController
  before_action :set_driver, only: %i[show edit]
  before_action :set_driver_update, only: %i[update]

  def index; end

  def approve
    @bookings = Booking.where('status=?', 'Pending').to_a
    driver = Driver.select('id').find_by(user_id: current_user.id)
    booked = Booking.where('driver_id=? AND status=?', driver.id, 'Booked')
    driver_rejects = DriverRequest.where('driver_id=?', driver.id)

    unless driver_rejects.empty?
      @bookings = @bookings.reject do |booking|
        driver_rejects.any? do |driver_reject|
          booking.id == driver_reject.booking_id
        end
      end
    end

    unless booked.empty?
      copy_booking = @bookings
      # byebug
      copy_booking = copy_booking.reject do |booking|
        booked.any? do |book|
          booking.from <= book.from && booking.to <= book.from
        end
      end

      copy_booking = copy_booking.reject do |booking|
        booked.any? do |book|
          booking.from >= book.to && booking.to >= book.to
        end
      end

      @bookings = @bookings.reject do |booking|
        copy_booking.any? do |book|
          booking.id == book.id
        end
      end
    end

    # byebug
  end

  def show_booking
    driver = Driver.select('id').find_by(user_id: current_user.id)
    @bookings = Booking.where('driver_id=?', driver.id)
  end

  def new; end

  def update
    if @driver.update(driver_params)
      flash[:success] = 'Driver Details Updated Succesfully'
      redirect_to root_path
    else
      render :new
    end
  end

  def show; end

  private

  def set_driver
    @driver = Driver.find_by(user_id: params[:id])
  end

  def set_driver_update
    @driver = Driver.find(params[:id])
  end

  def driver_params
    params.require(:driver).permit(:licence, :experience, :salary, :licence_driver_image, :driver_image)
  end
end

app/helpers/drivers_helper.rb
# frozen_string_literal: true

module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_with(model: driver, local: true) do |f| %>
  <div class="field">
    <%= f.label :licence_no %>
    <%= f.text_field :licence, required: true %>
  </div>
  <br/>

  <div class="field">
    <%= f.label :experience_years %>
    <%= f.text_field :experience, required: true %>
  </div>
  <br/>

  <% if current_user.has_role? :superadmin %>  
    <div class="field">
      <%= f.label :salary %>
      <%= f.number_field :salary, required: true %>
    </div>
    <br/>
  <%end%>
  
  <div class="field">
    <%= f.label :licence_image %>
    <%= f.file_field :licence_driver_image %><br><br>
  </div>
  <br/>

  <div class="field">
    <%= f.label :driver_image %>
    <%= f.file_field :driver_image %><br><br>
  </div>
  <br/>
  
  <div class="actions">
    <%=f.submit "Update Driver Details", {class: "btn btn-primary mb-2 btn-lg"}%>
  </div>
<%end %>

app/views/drivers/_header.html.erb
<%= link_to "Approval Requests",driver_approval_path %>
<%= link_to "My Bookings",show_booking_drivers_path %>
<%= link_to "Generate Bill",bills_path %>

app/views/drivers/approve.html.erb
<h1>Approval</h1>


<div class="travel">
  <table  class="table table-striped table-dark">
    <thead class = "bg-info">
      <tr>
        <th>From</th>
        <th>To</th>
        <th>Fuel</th>
        <th>Driver Present</th>
        <th>Car Drop Off At<br/> Different Location</th>
        <th>Booking Details</th>
        <th>Approve</th>
        <th>Disapprove</th>
      </tr>
    </thead>

    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.from.strftime("%a, %d-%b-%Y:  %I:%M %p") %></td>
          <td><%=  booking.to.strftime("%a, %d-%b-%Y:  %I:%M %p") %></td>
          <td><%= booking.fuel %></td>
          <td><%= booking.want_driver.humanize %></td>
          <td><%= booking.diff_city.humanize %></td>
          <td><%= link_to 'View Booking Details', travel_path(booking.id),class: "btn btn-outline-light" %></td>
          <td> <%= link_to request_accepted_path(booking) do  %>
          <%= '<i class="fa fa-check-circle-o text-success fa-2x" aria-hidden="true"></i>'.html_safe %>
          <% end %> </td>
          <td> <%= link_to request_rejected_path(booking) do  %>
            <%= '<i class="fa fa-times-circle-o text-danger fa-2x" aria-hidden="true"></i>'.html_safe %>
          <% end %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/drivers/edit.html.erb
<h1>Editing Driver Details</h1>

<%= render 'form', driver: @driver %><br/><br/>
<%= link_to 'Back To Home', root_path %>

app/views/drivers/index.html.erb
<h1>Welcome Driver</h1>
<p>Driver Logged In Page</p>

app/views/drivers/new.html.erb
<h1>New Licence</h1>

<%= render 'form', driver: @driver %><br/><br/>
<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<h1>Driver Details</h1>

<h2>Licence Number:&nbsp;&nbsp;<%= @driver.licence %></h2>
<h2>Experience:&nbsp;&nbsp;<%= @driver.experience %>&nbsp;years</h2>
<h2>Salary:&nbsp;&nbsp;&#8377;&nbsp;<%= @driver.salary %></h2>
<h2>Licence Image:&nbsp;&nbsp;<%= image_tag(@driver.licence_driver_image, style:"width:25%") if @driver.licence_driver_image.attached?%></h2>
<h2>Driver Image:&nbsp;&nbsp;<%= image_tag(@driver.driver_image, style:"width:20%") if @driver.driver_image.attached?%></h2>
<%= link_to "Edit Details", edit_driver_path(current_user.id), {class: "btn btn-primary mb-2 btn-lg"} %>



<% if @driver.licence == nil %>
  <h2>Tell Admin About Salary Details</h2>  
  <%= link_to 'Add Details', edit_driver_path, class: "btn btn-outline-primary btn-lg" %>
<% end %>
  
  
  

app/views/drivers/show_booking.html.erb
<h1>Booking Details</h1>

<div class="travel">
  <table  class="table table-striped table-dark">
    <thead class = "bg-info">
      <tr>
        <th>From</th>
        <th>To</th>
        <th>Status</th>
        <th>Fuel</th>
        <th>Driver Present</th>
        <th>Car Drop Off At<br/> Different Location</th>
        <th>Bookin Details</th>
      </tr>
    </thead>

    <tbody>
      <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.from.strftime("%a, %d-%b-%Y:  %I:%M %p") %></td>
          <td><%=  booking.to.strftime("%a, %d-%b-%Y:  %I:%M %p") %></td>
          <td><%= booking.status %></td>
          <td><%= booking.fuel %></td>
          <td><%= booking.want_driver.humanize %></td>
          <td><%= booking.diff_city.humanize %></td>
          <td><%= link_to 'View Booking Details', travel_path(booking.id),class: "btn btn-outline-light" %></td>
        </tr>
     <% end %>
    </tbody>
  </table>
</div>