config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboards#index'

  devise_for :users

  get 'admins/index'
  get 'superadmins/index'

  get 'bookings/show'
  get 'bookings/book/:id' => 'bookings#create_booking', as: :create_booking
  get 'addresses/create/:id' => 'addresses#new', as: :create_address
  get 'view_user' => 'users#view', as: :view_user
  get 'view_addr/:id' => 'users#view_addr', as: :view_addr
  get 'driver/approve' => 'drivers#approve', as: :driver_approval
  get 'driver/request_approved/:id' => 'driver_requests#accept_request', as: :request_accepted
  get 'driver/request_rejected/:id' => 'driver_requests#reject_request', as: :request_rejected

  # get 'superadmins/add_driver' => "superadmins#add_driver", as: :add_driver
  # post 'bookings/book/:id' => "bookings#create_booking", as: :create_booking
  # get "users/show/:id" => "users#show", as: :show_user

  resources 'drivers' do
    get 'show_booking', on: :collection, action: 'show_booking', as: :show_booking
  end
  resources 'bills', except: :new do
    get 'new_bill/:id', on: :collection, action: 'new', as: :new_bill
    get 'bill_pdf/:id', on: :collection, action: 'bill_pdf', as: :bill_pdf, defaults: { format: 'pdf' }
  end
  resources 'bookings' do
    get 'view_booking', on: :collection, action: 'view_booking', as: :view_booking
  end
  resources 'addresses'
  resources 'travels'
  resources 'cars'
  resources 'car_types'
  resources 'car_fuels'
  resources 'users', except: :create do
    post 'create_user', on: :collection, action: 'create', as: :create_user
  end
  resources 'customers'
  resources 'dashboards', only: [:index] do
    get 'about', on: :collection, action: 'about', as: :about
    get 'contact', on: :collection, action: 'contact', as: :contact
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/car.rb
# frozen_string_literal: true

class Car < ApplicationRecord
  belongs_to :car_type
  belongs_to :car_fuel
  has_many :bookings  

  FUEL = CarFuel.select(:name).distinct
  TYPE = CarType.select(:name).distinct

  validates :model, 
            uniqueness: true,
            format: {with: /\A[A-Z]{2}\s\d{2}\s[A-Z]{2}\s\d{4}\Z/,
            message: "Invalid Format Of Model..!!"},
            presence: true

  scope :searching, lambda { |s| 
  Car.joins(:car_type, :car_fuel).where('cars.name LIKE ? OR cars.model LIKE ? OR car_types.name LIKE ? OR car_fuels.name LIKE ? ', "%#{s}%", "%#{s}%", "%#{s}%", "%#{s}%") }

end

app/models/car_type.rb
# frozen_string_literal: true

class CarType < ApplicationRecord
  has_many :cars

  validates :name, uniqueness: true
end

app/controllers/cars_controller.rb
# frozen_string_literal: true

class CarsController < ApplicationController
  before_action :set_car, only: %i[show edit update destroy]

  def index
    @cars = Car.includes(:car_type, :car_fuel).paginate(page: params[:page], per_page: params[:per_page])
    if params[:query].present?
      @cars = Car.searching(params[:query]).paginate(per_page: params[:per_page], page: params[:page])
      # @cars = @cars.paginate(:per_page => 5, :page => params[:page])
      else
      @cars = Car.all.paginate(per_page: params[:per_page], page: params[:page])
      # @cars = @cars.paginate(:per_page => 5, :page => params[:page])
    end
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    @car.avail = true
    respond_to do |format|
      if @car.save
        flash[:success] = 'Car Created Successfully'
        format.html { redirect_to new_car_path }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @car.update(car_params)
        flash[:success] = 'Car Updated Successfully'
        format.html { redirect_to  cars_path }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
    end
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:name, :seats, :luggage, :min_kms, :cost_per_km, :car_type_id, :model, :car_fuel_id)
  end
end

app/helpers/cars_helper.rb
# frozen_string_literal: true

module CarsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: car, local: true) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field" style="display:inline-block">
    <%= f.label :car_type%>
    <%= f.collection_select :car_type_id, CarType.all,:id,:name %>
  </div>
  <br/><br/>
  <div class="field" style="display:inline-block">
    <%= f.label :car_fuel%>
    <%= f.collection_select :car_fuel_id, CarFuel.all,:id,:name %>
  </div>
  <br/><br/>
  <div class="field" style="display:inline-block">
    <%= f.label :name%>
    <%= f.collection_select :name, Car.select(:name).distinct,:name, :name %>
  </div>
  <br/><br/>
  <div class="field" style="display:inline-block">
    <%= f.label :no_of_seats%>
    <%= f.collection_select :seats,Car.select(:seats).distinct, :seats, :seats %>
  </div>
  <br/><br/>
  <div class="field" style="display:inline-block">
    <%= f.label :Luggage_Capacity%>
    <%= f.collection_select :luggage,Car.select(:luggage).distinct, :luggage, :luggage %>
    <%= f.label "(In Litres)"%>
  </div>
  <br/><br/>
  <div class="field" style="display:inline-block">
    <%= f.label :Minimum_Kms%>
    <%= f.collection_select :min_kms, Car.select(:min_kms).distinct, :min_kms, :min_kms %>
  </div>
  <br/><br/>
  <div class="field" style="display:inline-block">
    <%= f.label "Cost Per Kilometer"%>
    <%= f.collection_select :cost_per_km, Car.select(:cost_per_km).distinct, :cost_per_km, :cost_per_km %>
  </div>
  <br/><br/>
  <div class="field" style="display:inline-block">
    <%= f.label "Model Number: "%>
    <%= f.text_field :model %>
  </div>
  <br/><br/>
  <div class="actions">
    <%=f.submit "Add Car", {class: "btn btn-primary mb-2 btn-lg"}%>
  </div>
<% end %>

app/views/cars/_links_car.html.erb
<%= link_to 'Add Car Fuel',new_car_fuel_path, class: "btn btn-outline-primary btn-lg float-right mx-2" %>
<%= link_to 'View Car Fuels',car_fuels_path	, class: "btn btn-outline-primary btn-lg float-right mx-2" %>
<%= link_to 'Add Car Type',new_car_type_path, class: "btn btn-outline-primary btn-lg float-right mx-2" %>
<%= link_to 'View Car Types',car_types_path	, class: "btn btn-outline-primary btn-lg float-right mx-2" %>
<%= link_to 'Add Car',new_car_path, class: "btn btn-outline-primary btn-lg float-right mx-2" %>
<%= link_to 'View Cars',cars_path, class: "btn btn-outline-primary btn-lg float-right mx-2" %>
<br/><br/><br/><br/>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %><br/><br/>
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<%= render 'links_car' %>

<h1>All Cars</h1>

<%= form_tag("/cars", method: "get", remote: false, class:'form-inline md-form mr-auto mb-4 ml-5') do %>
  <%= text_field_tag :query, params[:query], class: "form-control mr-sm-2" %>
  <button class="btn btn-dark" type="submit">Search</button>
<% end %>

<h2>Select Number Of Cars To Be Displayed Per Page
  <%= select_tag :per_page, options_for_select([30,5,10,20,25],params[:per_page].to_i),
                :onchange => "if(this.value){window.location='?per_page='+this.value;}" %>
</h2>

<table class="table table-striped table-dark">
  <thead class = "bg-info">
    <tr>
      <th>Name</th>
      <th>Seats</th>
      <th>Luggage</th>
      <th>Minimum<br/>Kilometers</th>
      <th>Cost Per<br/>Kilometer</th>
      <th>Availability</th>
      <th>Car Type: Fuel</th>
      <th>Model</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.name %></td>
        <td><%=  car.seats%></td>
        <td><%= car.luggage  %></td>
        <td><%= car.min_kms %></td>
        <td> <%= car.cost_per_km %></td>
        <td> <%= car.avail.humanize %> </td>
        <td> <%= car.car_type.name%>: <%=car.car_fuel.name %> </td>
        <td> <%= car.model %> </td>
        <td> <%= link_to edit_car_path(car) do  %>
          <%= '<i class="fa fa-pencil-square-o text-light" aria-hidden="true"></i>'.html_safe %>
        <% end %></td>
        <td> <%= link_to car, method: :delete, data: { confirm: 'Are you sure?' } do  %>
          <%= '<i class="fa fa-trash text-light" aria-hidden="true"></i>'.html_safe %>
        <% end %></td>
      </tr>
    <% end %>
  </tbody>
</table>
    
<%= page_entries_info @cars %>
<%= will_paginate @cars, renderer: BootstrapPagination::Rails %>

app/views/cars/new.html.erb
<%= render 'links_car' %>
<br/><br/>
<h1>New Car</h1>

<%= render 'form', car: @car %>